const seedPosts = [
  {id:1, category:'Подорожі', date:'24 вересня 2026', title:'Місто, яке найкраще читати пішки', author:'Олена Руденко', excerpt:'Ужгород відкривається не в путівниках, а між кавовими двориками, старими мостами та неспішними маршрутами.', content:`Ужгород не намагається справити враження за перші п’ять хвилин. Тут немає потреби ставити галочки біля пам’яток, бо найцікавіше живе у проміжках: у запаху мокрого каменю після дощу, у виноградній лозі на чужому балконі, у коті, який безпомилково знає найтеплішу лавку на набережній.\n\nПочніть з ранку без маршруту. Перейдіть пішохідний міст, поверніть у першу тиху вуличку й дозвольте собі заблукати. Ужгород компактний і доброзичливий: тут заблукати означає знайти маленьку книгарню, стару браму чи кав’ярню, де розмовляють так, ніби ви вже давно знайомі.\n\nМожливо, саме це і є ознака хорошого міста: воно не вимагає від вас бути туристом. Воно дозволяє просто бути присутнім.`},
  {id:2, category:'Наука', date:'21 вересня 2026', title:'Чому дерева «розмовляють» повільніше за нас', author:'Максим Левченко', excerpt:'Під землею існує складна мережа грибниць, через яку ліс обмінюється поживними речовинами й сигналами.', content:`Ліс здається тихим лише тому, що ми звикли вимірювати життя людськими темпами. Для дерева один сезон — це речення, десятиліття — абзац, а повалений стовбур може лишатися частиною розмови ще багато років.\n\nКоріння дерев часто пов’язане з грибницею. Ці тонкі нитки допомагають передавати воду й мінерали, а в окремих випадках — сигнали про небезпеку. Старі великі дерева можуть підтримувати молоді саджанці у затінку; не з великодушності в людському сенсі, а тому що ліс — система взаємних залежностей.\n\nКоли наступного разу будете в парку, не поспішайте називати дерева нерухомими. Вони просто працюють у масштабі, для якого нам бракує терпіння.`},
  {id:3, category:'Культура', date:'19 вересня 2026', title:'Книги, які не треба «встигати» прочитати', author:'Софія Кравець', excerpt:'Читання не змагання: кілька способів повернути собі задоволення від книжки без списків і провини.', content:`У кожного читача є книжка, яка дивиться з полиці трохи докірливо. Товста, важлива, давно куплена — і зовсім не та, яку хочеться відкрити сьогодні. Ми перетворили читання на список досягнень, хоча його найкраща властивість зовсім інша: воно вчить бути неефективними.\n\nСпробуйте обрати книжку не за рейтингом і не за потребою «закрити прогалину», а за одним реченням, яке не виходить із голови. Читайте паралельно дві: одну — для думки, іншу — для відпочинку. Кидайте те, що не працює. Книга не образиться.\n\nДобре прочитаний текст не додає бал до уявного лічильника. Він залишає після себе новий кут, з якого видно світ.`},
  {id:4, category:'Люди', date:'17 вересня 2026', title:'Майстер, який повертає речам друге життя', author:'Ігор Бондар', excerpt:'У невеликій львівській майстерні старі радіоприймачі, лампи й фотоапарати отримують ще один шанс на історію.', content:`У майстерні Андрія пахне пилом, оливою та деревом. На полицях — радіоли, які пам’ятають голоси з кухонь шістдесятих, настільні лампи з подряпинами й камери, що давно не бачили плівки. «Поламане — не завжди зіпсоване», — каже він, обережно вкручуючи крихітний гвинтик.\n\nНайважче в реставрації — не знайти деталь. Найважче вирішити, що зберегти. Надто блискуча поверхня бреше про вік речі, а надто багато «автентичності» перетворює її на музейний експонат. Андрій шукає баланс: щоб предмет знову працював, але не забував, де був.\n\nУ світі, де нове купують швидше, ніж лагодять старе, така робота — майже тиха форма оптимізму.`},
  {id:5, category:'Дім', date:'14 вересня 2026', title:'Вечеря з того, що вже є: мистецтво не купувати зайвого', author:'Дарина Погребняк', excerpt:'Одна полиця, трохи фантазії та просте правило: найкращі буденні страви часто народжуються без рецепта.', content:`Увечері холодильник часто видається порожнім не тому, що в ньому нічого немає, а тому, що там немає готової ідеї. Половинка лимона, банка квасолі, вчорашній рис, кілька зелених цибулин — це не «нічого». Це початок вечері.\n\nМій улюблений спосіб готувати — почати з одного запитання: що тут треба використати першим? Далі додаються текстури: щось хрустке, щось м’яке, щось кисле. Обсмажений рис із квасолею, лимонною цедрою та зеленню не виглядає як компроміс, коли його не порівнювати з ідеальною стравою з фотографії.\n\nКухня стає спокійнішою, коли ми перестаємо бачити в ній склад продуктів. І починаємо бачити можливості.`},
  {id:6, category:'Міста', date:'11 вересня 2026', title:'Три лавки, з яких видно Київ по-новому', author:'Роман Черненко', excerpt:'Не оглядові майданчики й не листівкові точки: місця, де місто можна побачити без поспіху та шуму.', content:`У великих містах є місця, які працюють як кнопка «пауза». Вони не завжди мають краєвид на весь горизонт, зате вміють змінити фокус. У Києві я збираю такі лавки, як інші збирають адреси ресторанів.\n\nПерша — біля старого схилу над Подолом, де чути трамвай, але майже не видно машин. Друга — на Русанівській набережній, у ранкову годину, коли вода віддзеркалює багатоповерхівки без жодного пафосу. Третя — на маленькій терасі в ботсаду, де місто раптом здається не гігантським, а людським.\n\nЛавка — дивовижно чесний винахід. Вона не обіцяє вражень, тільки дає час, щоб ви самі їх помітили.`},
  {id:7, category:'Наука', date:'8 вересня 2026', title:'Маленька фізика великого затишку', author:'Назар Мельник', excerpt:'Чому тепле світло, тиша та правильна відстань між меблями відчуваються як безпека — пояснює наука про середовище.', content:`Затишок не живе в магазині декору. Він виникає тоді, коли простір перестає вимагати від нас уваги. Око не натикається на різкі контрасти, тіло легко знаходить місце, де сісти, а світло не змагається з вечором.\n\nФізика тут дуже земна. Тепле світло нижчої колірної температури здається спокійнішим, бо нагадує захід сонця й вогонь. Текстиль поглинає частину звуків, тому кімната з килимом і шторами відчувається тихішою. А вільний прохід між речами дає мозку простий сигнал: тут безпечно рухатися.\n\nЗатишок — не про ідеальний інтер’єр. Він про невеликі рішення, які дозволяють видихнути.`},
  {id:8, category:'Люди', date:'5 вересня 2026', title:'Садівниця з п’ятого поверху', author:'Віра Синиця', excerpt:'Як балкон у звичайній багатоповерхівці став міні-садом, місцем зустрічей і приводом для сусідських розмов.', content:`На балконі пані Тамари росте понад сорок видів рослин. Томати, м’ята, декоративна кукурудза, лимонне дерево й навіть маленька ожина — усе це вміщується на кількох квадратних метрах п’ятого поверху. «Не треба чекати на власний двір», — усміхається вона.\n\nЇї сад почався з двох горщиків базиліку під час довгого карантину. Тепер сусіди приносять насіння, питають поради, зупиняються поговорити. Виявилося, що зелень на вікні — ще й спосіб зробити під’їзд менш анонімним.\n\nМожливо, найцінніший врожай такого саду не поміщається в кошик. Це звичка помічати, як росте щось живе — і як через нього оживають зв’язки між людьми.`},
  {id:9, category:'Культура', date:'2 вересня 2026', title:'Листи самому собі: навіщо писати від руки', author:'Марко Яремчук', excerpt:'Ручка й папір не повертають нас у минуле — вони створюють інший, повільніший спосіб почути власну думку.', content:`Екран терпляче підказує наступне слово, виправляє помилки й зберігає майже все. Папір нічого не підказує. Саме тому інколи він чесніший. Коли пишеш від руки, думка не може обігнати рух пальців — доводиться трохи почекати на себе.\n\nЯ завів звичку щонеділі писати короткий лист людині, якою був сім днів тому. Не звіт і не список справ: радше кілька речень про те, що здивувало, засмутило або вийшло краще, ніж очікувалось. Через місяць ці листи складаються не в щоденник, а в розмову.\n\nНе обов’язково робити почерк красивим чи думки глибокими. Достатньо залишити для себе місце, де ніхто не натискає «відправити».`},
  {id:10, category:'Подорожі', date:'29 серпня 2026', title:'Як поїхати на вихідні й не перетворити відпочинок на проєкт', author:'Анна Ткаченко', excerpt:'Три прості межі для короткої поїздки: менше точок на карті, більше повітря у плані та жодного обов’язкового захоплення.', content:`Коротка подорож легко стає мініатюрною версією робочого тижня: таблиця, таймінг, список «обов’язково побачити», тривога через запізнення. Але вихідні не повинні доводити свою ефективність.\n\nПеред поїздкою я обираю лише одну головну причину їхати. Це може бути озеро, музей, нове місто або зустріч із подругою. Усе інше — необов’язкове. Такий план має запас повітря: можна засидітися за сніданком, пропустити «топову» локацію чи раптово змінити маршрут.\n\nПовернутися з поїздки не з усіма фотографіями, а з відчуттям, що день належав вам, — набагато кращий сувенір.`}
];

const store = { get: (key, fallback) => { try { return JSON.parse(localStorage.getItem(key)) ?? fallback; } catch { return fallback; } }, set: (key, value) => localStorage.setItem(key, JSON.stringify(value)) };
let currentFilter = 'Усі';
let currentQuery = '';
const $ = (selector) => document.querySelector(selector);
const grid = $('#postGrid');
const escapeHtml = (value) => String(value).replace(/[&<>'"]/g, char => ({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[char]));
const allPosts = () => [...store.get('skyblog.customPosts', []), ...seedPosts];

function renderPosts() {
  const posts = allPosts().filter(post => (currentFilter === 'Усі' || post.category === currentFilter) && `${post.title} ${post.excerpt} ${post.author}`.toLowerCase().includes(currentQuery.toLowerCase()));
  $('#postCount').textContent = allPosts().length;
  grid.innerHTML = posts.map(post => `<article class="post-card"><div class="card-meta"><span>${escapeHtml(post.category)}</span><time>${escapeHtml(post.date)}</time></div><h3><button type="button" data-read="${post.id}">${escapeHtml(post.title)}</button></h3><p class="excerpt">${escapeHtml(post.excerpt)}</p><div class="card-bottom"><span class="author">${escapeHtml(post.author)}</span><button class="read-button" type="button" data-read="${post.id}" aria-label="Читати: ${escapeHtml(post.title)}">→</button></div></article>`).join('');
  $('#emptyState').hidden = posts.length !== 0;
}

function showArticle(id) {
  const post = allPosts().find(item => String(item.id) === String(id));
  if (!post) return;
  $('#articleContent').innerHTML = `<p class="article-category">${escapeHtml(post.category)}</p><h2 id="articleTitle">${escapeHtml(post.title)}</h2><p class="article-meta">${escapeHtml(post.author)} · ${escapeHtml(post.date)}</p><div class="article-body">${escapeHtml(post.content).split(/\n\n+/).map(p => `<p>${p}</p>`).join('')}</div>`;
  $('#articleModal').showModal();
}

function setAuthMode(mode) {
  const login = mode === 'login';
  $('#loginForm').hidden = !login; $('#registerForm').hidden = login;
  $('#authTitle').textContent = login ? 'Раді вас бачити' : 'Створіть свій куточок';
  $('#authLead').textContent = login ? 'Увійдіть, щоб публікувати власні історії.' : 'Збережіть свій голос у спільноті Skyblog.';
}
function openAuth(mode = 'login') { setAuthMode(mode); $('#loginMessage').textContent = ''; $('#registerMessage').textContent = ''; $('#authModal').showModal(); }
function session() { return store.get('skyblog.session', null); }
function renderHeader() {
  const user = session(); const holder = $('#headerActions');
  if (!user) { holder.innerHTML = '<button class="button button-quiet" id="loginButton" type="button">Увійти</button><button class="button button-primary" id="registerButton" type="button">Створити акаунт</button>'; $('#loginButton').onclick = () => openAuth('login'); $('#registerButton').onclick = () => openAuth('register'); return; }
  holder.innerHTML = `<div class="user-menu"><span class="user-badge">Привіт, ${escapeHtml(user.name)}</span><span class="user-avatar" aria-hidden="true">${escapeHtml(user.name.slice(0,1).toUpperCase())}</span><button class="button button-quiet" id="logoutButton" type="button">Вийти</button></div>`;
  $('#logoutButton').onclick = () => { localStorage.removeItem('skyblog.session'); renderHeader(); };
}
function openCompose() { if (session()) { $('#postMessage').textContent = ''; $('#composeModal').showModal(); } else openAuth('login'); }

document.addEventListener('click', event => {
  const filter = event.target.closest('[data-filter]'); if (filter) { currentFilter = filter.dataset.filter; document.querySelectorAll('.filter').forEach(button => button.classList.toggle('active', button === filter)); renderPosts(); }
  const reader = event.target.closest('[data-read]'); if (reader) showArticle(reader.dataset.read);
  if (event.target.matches('[data-close]')) event.target.closest('dialog').close();
  const switcher = event.target.closest('[data-switch]'); if (switcher) setAuthMode(switcher.dataset.switch);
});
$('#searchInput').addEventListener('input', event => { currentQuery = event.target.value; renderPosts(); });
$('#heroWriteButton').onclick = openCompose; $('#contributeButton').onclick = openCompose;
$('#loginForm').addEventListener('submit', event => { event.preventDefault(); const users = store.get('skyblog.users', []); const user = users.find(item => item.email.toLowerCase() === $('#loginEmail').value.trim().toLowerCase() && item.password === $('#loginPassword').value); if (!user) { $('#loginMessage').textContent = 'Не вдалося знайти акаунт або пароль не збігається.'; return; } store.set('skyblog.session', {name:user.name,email:user.email}); $('#authModal').close(); renderHeader(); });
$('#registerForm').addEventListener('submit', event => { event.preventDefault(); const users = store.get('skyblog.users', []); const email = $('#registerEmail').value.trim().toLowerCase(); if (users.some(item => item.email === email)) { $('#registerMessage').textContent = 'Акаунт із такою поштою вже існує.'; return; } const user = {name:$('#registerName').value.trim(), email, password:$('#registerPassword').value}; users.push(user); store.set('skyblog.users', users); store.set('skyblog.session', {name:user.name,email:user.email}); $('#registerForm').reset(); $('#authModal').close(); renderHeader(); openCompose(); });
$('#postForm').addEventListener('submit', event => { event.preventDefault(); const user = session(); if (!user) return openAuth(); const post = {id:`custom-${Date.now()}`,category:$('#postCategory').value,date:new Intl.DateTimeFormat('uk-UA',{day:'numeric',month:'long',year:'numeric'}).format(new Date()),title:$('#postTitle').value.trim(),author:user.name,excerpt:$('#postExcerpt').value.trim(),content:$('#postContent').value.trim()}; const posts = store.get('skyblog.customPosts',[]); posts.unshift(post); store.set('skyblog.customPosts',posts); $('#postForm').reset(); $('#composeModal').close(); currentFilter='Усі'; document.querySelectorAll('.filter').forEach(button => button.classList.toggle('active', button.dataset.filter === 'Усі')); renderPosts(); document.querySelector('#posts').scrollIntoView({behavior:'smooth'}); setTimeout(() => showArticle(post.id), 550); });
document.querySelectorAll('dialog').forEach(dialog => dialog.addEventListener('click', event => { if (event.target === dialog) dialog.close(); }));
renderPosts(); renderHeader();
